services:
  app:
    container_name: manunggal-app
    build:
      context: .
      dockerfile: DockerFile
    restart: unless-stopped
    tty: true
    ports:
      - "127.0.0.1:3000:80"
    deploy:
      resources:
        limits:
          memory: 256MB
    mem_limit: 256MB
